In [1]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [1]:
pwd

'C:\\Users\\lahari'

In [4]:
def f(s):
    l=list(s.split())
    l1=" "
    for i in l:
        if i=='one':
            l1+='1'
        elif i=='two':
            l1+='2'
        elif i=='three':
            l1+='3'
        elif i=='four':
            l1+='4'
        elif i=='five':
            l1+='5'
        elif i=='six':
            l1+='6'
        elif i=='seven':
            l1+='7'
        elif i=='eight':
            l1+='8'
        elif i=='nine':
            l1+='9'
        else:
            l1+='0'
    print(l1)
s=input()
f(s)

one two
 12


In [4]:
x=[9,4,8,2,3]
y=[]
for i in range(len(x)-1):
    if x[i]>max(x[i+1:]):
        y.append(x[i])
print(y)

[9, 8]


In [ ]:
x=[89,2,34,5,7,8]
l=[]
for i in range(len(x)-1):
    if x[i]>max(x[i+1:]):
        l.append(x[i])
l.append(x[-1])
print(l)

In [7]:
n=int(input())
for i in range(n):
    if i*(i+1)==n:
        print('pronic no')
        break
else:
    print('not')

72
pronic no


In [2]:
x=y=[1,2,3]
x=[4,5,6]

In [3]:
print(x)

[4, 5, 6]


In [4]:
x[0]=7

In [5]:
print(y)

[1, 2, 3]


In [7]:
x=y=[9,8,7]
x[0]=13
print(y)

[13, 8, 7]


In [8]:
def my_function():    # This is a function definition. Note the colon (:)
 a = 2                # This line belongs to the function because it's indented
 return a             # This line also belongs to the same function
print(my_function())  #this line is out of fn

2


In [9]:
a=2
b=3
if a>b: print(a)
else:print(b)

3


In [10]:
l="neeraj"
print(reversed(l))

In [11]:
a=reversed("hello")
print(a)

In [ ]:
a = (1, 2, 3)
b = ('a', 1, 'python', (1, 2))
print(b(2))

In [2]:
a=7
if isinstance(a,int):
    a+=1
elif isinstance(a,str):
    a=int(a)
    a+=1
print(a)

8


In [3]:
b'foo bar'

b'foo bar'

In [4]:
u'foo bar'

'foo bar'

In [5]:
r'foo bar'

'foo bar'

In [7]:
print('foo\\nbar')

foo\nbar


In [8]:
print(r'foo\\nbar')

foo\\nbar


In [9]:
print('foo\nbar')

foo
bar


In [11]:
def f(m):
 m.append(3) # adds a number to the list. This is a mutation.
x = [1, 2]
f(x)
x==[1,2]

False

In [13]:
a=[1,2,3,4]
a.reverse()
print(a)

[4, 3, 2, 1]


In [25]:
a={'1':'k','2':'h','3':'a','4':'r'}
for x in a:
    print('{} format is{}'.format(a[x],x))

k format is1
h format is2
a format is3
r format is4


In [23]:
state_capitals = {
 'Arkansas': 'Little Rock',
 'Colorado': 'Denver',
 'California': 'Sacramento',
 'Georgia': 'Atlanta'
}
for k in state_capitals.keys():
    print('{} is the capital of {}'.format(state_capitals[k],k))

Little Rock is the capital of Arkansas
Denver is the capital of Colorado
Sacramento is the capital of California
Atlanta is the capital of Georgia


In [26]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [27]:
help(SyntaxError)

Help on class SyntaxError in module builtins:

class SyntaxError(Exception)
 |  Invalid syntax.
 |  
 |  Method resolution order:
 |      SyntaxError
 |      Exception
 |      BaseException
 |      object
 |  
 |  Built-in subclasses:
 |      IndentationError
 |  
 |  Methods defined here:
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __str__(self, /)
 |      Return str(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  filename
 |      exception filename
 |  
 |  lineno
 |      exception lineno
 |  
 |  msg
 |      exception msg
 |  
 |  offset
 |      exception offset
 |  
 |  print_file_and_line
 |      exception print_file_and_line
 |  
 |  text
 |      exception text
 |  
 |  ----------------------------------------------------------------------
 |  Static methods inherited from Exception:
 |  
 |  __new__(*args, **kwargs) fr

In [28]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [29]:
import math
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [35]:
import hello.txt
hello.txt.say_hello()

ModuleNotFoundError: No module named 'hello'

In [1]:
s="wow"
print(repr(s))

'wow'


In [1]:
s="wow"
print(s)

wow


In [2]:
print(eval(repr(s))==s)

True


In [3]:
print(str(s))

wow


In [4]:
print(eval(str(s))==s)

NameError: name 'wow' is not defined

In [6]:
import datetime
today = datetime.datetime.now()
str(today) 


'2021-05-31 20:56:11.612027'

In [7]:
repr(today)

'datetime.datetime(2021, 5, 31, 20, 56, 11, 612027)'

In [14]:
def greet(name,greeting):
    print("{}{}".format(greeting,name))
name="neeraj"
greeting="i miss u "
greet(name,greeting)

i miss u neeraj


In [16]:
def greeting(name):
    print("hello "+name)
name="thanu"
greeting(name)

hello thanu


In [4]:
n=int(input())
x=[int(a) for a in str(n)]
print(x)
sum=0
for i in x:
    if i%2==0:
        sum=sum+i
print(sum)

45621
[4, 5, 6, 2, 1]


In [12]:
n=input()
sum=0
for i in x:
    if i%2==0:
        sum=sum+i
print(sum)   

45621
12


In [13]:
n=int(input())
n=str(n)
for i in range(len(n)):
    if i%2==0:
        print(n[i],end="")

12344587
1348

In [11]:
n1=input()
n2=input()
for i in n1:
    for j in n2:
        if(i==j):
            print(i,end="")

12378
34215
123

In [16]:
n=input()
if n==n[::-1]:
    print("palindrome",n)
else:
    print("not palindrome")     

123
not palindrome


In [18]:
x=list(map(int,input().split()))
print(x)

1 2 3 4
[1, 2, 3, 4]


In [25]:
l=[]
for i in range(10):
    x=input()
    l.append(x)
print(l)

1
2
3]
4
5
6
7
8
9
0
['1', '2', '3]', '4', '5', '6', '7', '8', '9', '0']


In [6]:
class Sol:
    def countsubstrings(self,s):
        count=0
        for i in range(len(s)):
            for j in range(i+1,len(s)+1):
                temp=s[i:j]
                if temp==temp[::-1]:
                    count+=1
                    print(temp)
        return count
obj1=Sol()
string=input()
print(obj1.countsubstrings(string))

aaaa
a
aa
aaa
aaaa
a
aa
aaa
a
aa
a
10


In [7]:
m=int(input())
n=int(input())
matrix=[]
for i in range(m):
        row=[]
        for j in range(n):
             row.append(int(input()))
        matrix.append(row)
print(matrix.diagonal())

3
3
1
2
3
4
5
6
7
8
9


AttributeError: 'list' object has no attribute 'diagonal'

In [8]:
import numpy as np
a = np.arange(9).reshape((3,3))

print(' Matrix a : ', a)
print('Diagonal of Matrix a : ', np.diag(a))

 Matrix a :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
Diagonal of Matrix a :  [0 4 8]


In [9]:
lis = []
lis2 = []
count = len(a)-1
count2 = 0
for i in range(len(a)):
    lis.append(a[count2][count])
    count-=1
    count2+=1
for i in range(len(a)):
    lis2.append(a[i][i])

print(lis,lis2)

[2, 4, 6] [0, 4, 8]


In [13]:
string=input().split()
print(string)
print(len(string),"words")

how are you thanu
['how', 'are', 'you', 'thanu']
4 words


In [15]:
def count_string(string):
    count=0
    for i in string:
        count+=1
    return count
string=input().split()
print(count_string(string),"words")

how are you thanu
4 words


In [31]:
string=input()
vowels=[]
for i in string:
    if i=='a' or i=='e' or i=='i' or i=='o' or i=='u':
        vowels.append(i)
    else:
        vowels.append("#")
print(vowels)

hai hello how r u
['#', 'a', 'i', '#', '#', 'e', '#', '#', 'o', '#', '#', 'o', '#', '#', '#', '#', 'u']


In [28]:
string=input()
vowels=[i for i in string if i=='a' or i=='e' or i=='i' or i=='o' or i=='u']
print(vowels)

hai hello how r u
['a', 'i', 'e', 'o', 'o', 'u']


In [34]:
string=input()
for i in string:
    if i=='a' or i=='e' or i=='i' or i=='o' or i=='u':
        print(i,end="")
    else:
        print("#",end="")

hai hello how r u
#ai##e##o##o####u

In [40]:
string=input()
if(string==string[::-1]):
    print(string,"is palindrome")
else:
    print(string,"is not palindrome")

Madam
Madam is not palindrome


print Madam is a palindrome

In [41]:
string=input()
string=string.upper()
if(string==string[::-1]):
    print(string,"is palindrome")
else:
    print(string,"is not palindrome")

Madam
MADAM is palindrome


1.Read a string check it is palindrome or not
2.if it is palindrome divide string into parts
3.check each part is palindrome or not.if both parts are palindrome we can print string is complete palindrome
4.if not print not a palindrome

In [4]:
string=input()
if string==string[::-1]:
    x=len(string)//2
    print(x)
    new_string=string[:x]+string[x+1:]
    print(new_string)
    if(new_string==new_string[::-1]):
        print("complete palindrome")
else:
    print("not a palindrome")

mmmm
2
mmm
complete palindrome


read a no(5676544)
sum of sum of digits of a no
(5+6+7+6+5+4+4)+(6+7+6+5+4+4)+(7+6+5+4+4)+(6+5+4+4)+(5+4+4)+(4+4)+4=139

In [5]:
(5+6+7+6+5+4+4)+(6+7+6+5+4+4)+(7+6+5+4+4)+(6+5+4+4)+(5+4+4)+(4+4)+4

139

In [12]:
n=int(input())
r=n
while(r!=0):
    rem=r%10
    rev=rev*10+r
    r=r/10
for i in num
while(rev!=0):
    rem=rev%10
    r1=r1*10+rem
    sum=sum+rem   

5676544
37


i/p-hollow
0/p-h,w

In [7]:
string=input().split(',')
string=set(string)
print(string)
string1=list(set(string))
print(string1)
print(string-string1)

KeyboardInterrupt: Interrupted by user

In [4]:
string=input()
l=[]
for i in string:
    l.append(i)
print(l)
l2=[]
for i in l:
    if l.count(i)==1:
        l2.append(i)
print(l2)
str1=" "
for x in l2:
    str1+=x
print(str1)

madanapalle
['m', 'a', 'd', 'a', 'n', 'a', 'p', 'a', 'l', 'l', 'e']
['m', 'd', 'n', 'p', 'e']
 mdnpe


In [27]:
string=input()
string=string.replace(" ","")
c=[]
v=[]
ss=[]
for i in range(len(string)):
    if (string[i].isalpha()) and (string[i] == 'a' or string[i]=='e' or string[i]=='i' or string[i]=='o' or string[i]=='u'):
           c.append(i)
    elif string[i].isalpha():
          v.append(i)
    else:
          ss.append(i)
    
print(len(c))
print(len(v))
print(len(ss))

hai! how r u thanu?
6
7
2


In [1]:
sss=input()
original = 'abcdefghijklmnopqrstuvwxyz'
reverse = 'zyxwvutsrqponmlkjihgfedcba'
dictChars = dict(zip(original,reverse))
mirror=''
for i in range(len(sss)):
    mirror=mirror+dictChars[sss[i]]
print(mirror)                               

abcd
zyxw


i/p--> 12345
o/p--> (1+2+3+4+5)+(

In [8]:
string='abcd'
print(string[::-1])

dcba


find palindromes in list of strings

In [2]:
array=list(map(str,input().split()))
print(array)
for i in array:
    if i==i[::-1]:
        print(i)

thanu madam rrr roopa lahal godog
['thanu', 'madam', 'rrr', 'roopa', 'lahal', 'godog']
madam
rrr
lahal
godog


In [6]:
array=list(map(str,input().split()))
print(sorted(array))

thanu ruo gyu hyt hjk
['gyu', 'hjk', 'hyt', 'ruo', 'thanu']


In [4]:
array=list(map(str,input().split()))
for i in array:
    print(i[-1])

thanu ruo gyu hyt hjk
u
o
u
t
k


In [7]:
class A:
    

SyntaxError: invalid syntax (<ipython-input-7-73eac5a1fc4f>, line 2)

In [ ]:
class Abc:
    

In [10]:
x="hai nhjm"
print(x.strip())

hai nhjm


In [11]:
print(x.replace(" ",""))

hainhjm


In [12]:
x="  hai njm"
print(x.strip())

hai njm


In [13]:
x="hai njm    "
print(x.strip())

hai njm


In [8]:
string=input()
out=''
for i in range(len(string)):
    if string[i].isalpha():
         out+=string[i]
print(out)

pro$#@gra7m
program


hello
(h-o)+(e-l)+(l)

In [52]:
alpha={'a':1,'b':2,'c':3,'d':4,'e':5,'f':6,'g':7,'h':8,'i':9,'j':10,'k':11,'l':12,'m':13,'n':14,'o':15,'p':16,'q':17,'r':18,'s':19,'t':20,'u':21,'v':22,'w':23,'x':24,'y':25,'z':26}
string=input().split()
s1=string[0]
s2=string[1]
print(s1)
print(s2)
out1=[]
out2=[]
for i in s1:
    out1.append(alpha.get(i))
print(out1)
for i in s2:
    out2.append(alpha.get(i))
print(out2)
x=set()
for i in range(len(out1)):
    x.add(abs(out1[i]-out1[(len(out1)-1)-i]))
print(sum(x))    

#for i in len(out):
    

hello world
hello
world
[8, 5, 12, 12, 15]
[23, 15, 18, 12, 4]
7


In [1]:
l=list(map(int,input().split()))
print(l)

1 2 3 4 5
[1, 2, 3, 4, 5]


In [3]:
temp=l[0]
l[0]=l[-1]
l[-1]=temp
print(l)

[5, 2, 3, 4, 1]


In [2]:
num1=int(input())
num2=int(input())
mul=num1*num2
if mul>1000:
    print(num1+num2)
else:
    print(mul)

40
30
70


In [4]:
for i in range(10):
    sum=i+(i-1)
    if(sum<0):
        print(0)
    else:
        print(sum)

0
1
3
5
7
9
11
13
15
17


In [6]:
string=input()
for i in range(len(string)):
    if(i%2==0):
        print(string[i])

pynative
p
n
t
v


In [2]:
string=input()
n=int(input())
print(string[n:])

pynative
4
tive


In [8]:
def fun(l):
    if l[0]==l[-1]:
        return True
    else:
        return False
l=list(map(int,input().split()))
print(fun(l))

10 2 3 4 5
False


In [10]:
l=list(map(int,input().split()))
l2=[]
for i in l:
    if i%5==0:
        l2.append(i)
print(l2)

10 20 3 4 5 80 85 7 
[10, 20, 5, 80, 85]


In [11]:
string="Emma is good developer. Emma is a writer"
print(string.count("Emma"))

2


In [14]:
num=input()
reverse=num[::-1]
if num==reverse:
    print("num&reverse are same")
else:
    print("num&reverse are not same")

121
num&reverse are same


In [17]:
l1=list(map(int,input().split()))
l2=list(map(int,input().split()))
l3=[]
for i in l1:
    if i%2==1:
        l3.append(i)
for j in l2:
    if j%2==0:
        l3.append(j)
print(l3)

10 2 3 4 5 7 9
10 2 3 4 5 7 9
[3, 5, 7, 9, 10, 2, 4]


In [19]:
num=input()
for i in num:
    rem=int(num)%10
    print(rem,end=" ")
    num=int(num)//10
    

1234
4 3 2 1 

In [24]:
n=int(input())
for i in range(1,n+1):
    for j in range(1,11):
        print(i*j,end=" ")
    print(" ")

10
1 2 3 4 5 6 7 8 9 10  
2 4 6 8 10 12 14 16 18 20  
3 6 9 12 15 18 21 24 27 30  
4 8 12 16 20 24 28 32 36 40  
5 10 15 20 25 30 35 40 45 50  
6 12 18 24 30 36 42 48 54 60  
7 14 21 28 35 42 49 56 63 70  
8 16 24 32 40 48 56 64 72 80  
9 18 27 36 45 54 63 72 81 90  
10 20 30 40 50 60 70 80 90 100  


In [25]:
base=int(input())
exp=int(input())
print(base**exp)

2
5
32


Abstraction
-hiding data/implementation and represent the functionality
-ex:ATM
-keywords: abstract&interface
-interface is suffiecient keyword
- 
abstract class A
{
abstract void add();
void sub();
{
/// concrete methods
(in a abstract class there is a method declaration along with definition)
}

}
-abstract class is partially implemented
-no,can't create object with abstract class due to partially implemented so we can't know memory required
-class is fully implemented we can analyse complete memory required for a class
-we use interface(ntg is implemented,everything is hidden) because it is concrete method for fully abstraction
-interface:collection of final variables(constant)&abstract methods 
-interface Abc
{
int a=30;
void add();
void sub();
}
interface Abc
{
public final static int a=30;
public abstract void add();
public abstract void sub();
}
one interface to other class-implementation

In [4]:
l=list(map(int,input().split()))
pos1=int(input())
pos2=int(input())
if pos1<len(l) and pos2<len(l):
    temp=l[pos1]
    l[pos1]=l[pos2]
    l[pos2]=temp
print(l)

1 2 3 4 6 7
1
4
[1, 6, 3, 4, 2, 7]


In [5]:
l=list(map(int,input().split()))
leng=0
for i in l:
    leng+=1
print(leng)

1 2 3 4 5
5


In [6]:
l=list(map(int,input().split()))
print(len(l))

1 2 3 4 5
5


In [11]:
l=list(map(int,input().split()))
max_=l[0]
for i in l:
    if i>max_:
        max_=i
print(max_)

1 5 3 9 2
9


In [12]:
l=list(map(int,input().split()))
min_=l[0]
for i in l:
    if i<min_:
        min_=i
print(min_)

1 5 3 9 2
1


In [26]:
l=list(map(int,input().split()))
n=int(input())
if n in l:
    print("exists")
else:
    print("no")

1 2 3 4
2
exists


In [31]:
l=list(map(int,input().split()))
l.clear()
print(l)

12 5 6
[]


In [36]:
l=list(map(int,input().split()))
for x in reversed(l):
    print(x,end=" ")

1 32 5 6
6 5 32 1 

In [37]:
l=list(map(int,input().split()))
x=[i for i in reversed(l)]
print(x)

7 6 5 4
[4, 5, 6, 7]


In [39]:
l=list(map(int,input().split()))
l.reverse()
print(l)

9 8 7 6
[6, 7, 8, 9]


In [40]:
l=list(map(int,input().split()))
print(l[::-1])

6 5 4 3
[3, 4, 5, 6]


In [41]:
l1=list(map(int,input().split()))
l2=[]
for i in l1:
    l2.append(i)
print(l2)

1 2 3 4
[1, 2, 3, 4]


In [42]:
l1=list(map(int,input().split()))
l2=l1.copy()
print(l2)

1 2 3 4
[1, 2, 3, 4]


In [43]:
l=list(map(int,input().split()))
for i in l:
    print(count(i))

1 2 2 3 4 5


NameError: name 'count' is not defined

In [45]:
l=list(map(int,input().split()))
n=int(input())
print(l.count(n))

1 2 2 2 2
2
4


In [46]:
l=list(map(int,input().split()))
n=int(input())
count=0
for i in l:
    if i==n:
        count+=1
print(count)

1 11 11 111 111 111
111
3


In [51]:
l=list(map(int,input().split()))
sum_=0
for i in l:
    sum_+=i
print(sum_)
print(sum_/len(l))

15 9 55 41 35 20 62 49
286
35.75


In [52]:
l=list(map(int,input().split()))
mul=1
for i in l:
    mul=mul*i
print(mul)

1 2 3 4
24


In [53]:
l=list(map(int,input().split()))
l.sort()
print(l[-2])

1 6 3 4 2 9
6


In [57]:
l=list(map(int,input().split()))
max_=l[0]
for i in l:
    if i>max_:
        max_=i
l.remove(max_)
print(l)
max_=l[0]
for i in l:
    if i>max_:
        max_=i
print(max_)

1 3 6 8 9 4 
[1, 3, 6, 8, 4]
8


In [58]:
l=list(map(int,input().split()))
for i in range(len(l)):
    if i%2==0:
        print(l[i])

1 2 3 4 5 6 7
1
3
5
7


In [59]:
l=list(map(int,input().split()))
for i in range(len(l)):
    if i%2==1:
        print(l[i])

1 2 3 4 5 6 7
2
4
6


In [61]:
l=list(map(int,input().split()))
for i in l:
    if i%2==0:
        print(i)

1 2 3 4 5 6
2
4
6


In [63]:
l=list(map(int,input().split()))
even=0
odd=0
for i in l:
    if i%2==0:
        even+=1
    else:
        odd+=1
print(even)
print(odd)

1 2 3 4 5 6
3
3


In [65]:
l=list(map(int,input().split()))
l1=[]
l2=[]
for i in l:
    if i not in l1:
        l1.append(i)
    else:
        l2.append(i)
print(l2)

1 2 2 3 3 4 4 5 5
[2, 3, 4, 5]


In [69]:
l=list(input().split())
l1=l[::-1]
s=''
for i in l1:
    s=s+i+" "
print(s)

hai how r u
u r how hai 


In [70]:
s=input()
n=int(input())
print(s[:n]+s[n+1:])

lahari
2
laari


In [73]:
s=input()
count=0
for i in s:
    count+=1
print(count)

hello
5


In [78]:
s=input()
l=s.split()
print(l)
for i in l:
    if len(i)%2==0:
        print(i)

ha hai ha hai
['ha', 'hai', 'ha', 'hai']
ha
ha


In [80]:
s=input()
s1=s.replace(" ","")
print(s1)

hai lahari
hailahari


In [8]:
s=input()
x=len(s)//2
print(x)
print(s[:x]+s[x:].upper())
print(s)

haigov
3
haiGOV
haigov


In [86]:
s=input()
print(s[0].upper()+s[1:-1]+s[-1].upper())

hello
HellO


In [88]:
def check(s):
x=False
y=False
for i in range(len(s)):
    if s[i].isalpha():
        x=True
    elif s[i].isdigit():
        y=True
return x and y


hai2


SyntaxError: 'return' outside function (<ipython-input-88-95b96c85b841>, line 9)

In [4]:
def multiple(m,n):
    if m==0 or n==0:
        return 3
    else:
        if m%n==0:
            return 2
        else:
            return 1
    
m=int(input()) #always +ve
n=int(input()) #may be +ve,-ve&0
multiple(m,n)

24
4


2

In [7]:
class A:
    def __init__(self,m,n):
        self.m=m
        self.n=n
    def multiple(self):
        if m==0 or n==0:
            return 3
        elif m%n==0:
            return 2
        else:
            return 1
m=int(input())
n=int(input())
d=A(m,n)
print(d.multiple())
        

0
4
3


Friendly pai or not:

In [44]:
n1=int(input())
n2=int(input())
sum1=0
sum2=0
for i in range(1,n1):
    if(n1%i==0):
        sum1+=i
for i in range(1,n2):
    if(n2%i==0):
        sum2+=i
print(sum1)
print(sum2)
if(sum1==n1 and sum2==n2):
    print("friendly pair")
else:
    print("non-friendly pair")

6
28
6
28
friendly pair


Automorphic number:

In [20]:
n=int(input())
sq=n*n
if sq%10==n%10:
    print("automorphic")
else:
    print("not automorphic")

5
automorphic


In [31]:
n=input()
x=len(n)
print(x)
y=int(n)
sq=y*y
print(sq)
sq=str(sq)
print(sq)
print(sq[-x:])
if sq[-x:]==n:
    print("yes")
else:
    print("no")

76
2
5776
5776
76
yes


In [36]:
n=int(input())
sq=n*n
n=str(n)
sq=str(sq)
print(sq)
x=len(n)
if sq[-x:]==n:
    print("yes")
else:
    print("no")

25
625
yes


take inpt string with only alphabets

In [45]:
s=input()
s1=""
for char in s:
    if ord(char)>=65 and ord(char)<=90:
        s1+=char
    elif ord(char)>=97 and ord(char)<=122:
        s1+=char
print(s1)

go2night
gonight


In [47]:
s=input()
s1=""
for char in s:
    if char.isalpha():
        s1+=char
print(s1)

go2NightT
goNightT


In [50]:
s=input()
s1=""
for char in s:
    if char.isalpha():
        s1+=char
print(s1)
s1=s1.upper()
if s1==s1[::-1]:
    print("palindrome")
else:
    print("not palindrome")

hai bro
haibro
not palindrome


In [51]:
str1=input()
str2=input()
print(int(str1)+int(str2))   

123456732128989543219
987612673489652
123457719741663032871


In [80]:
str1=input().split()
s=0
for i in str1:
    print(i,len(i))
    s=s+len(i)
print(s)
s1="%s"%s
print(type(s1))
print(len(s1))
if len(s1)!=0:
     

x y x
x 1
y 1
x 1
3
<class 'str'>
1


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [6]:
str1=input().split()
s=0
for i in str1:
    print(i,len(i))
    s=s+len(i)
print(s)
s1=str(s)
sum_=0
if len(s1)!=1:
    for i in s1:
        sum_=sum_+int(i)
print(sum_)
    

the good the bad anf the ugly
the 3
good 4
the 3
bad 3
anf 3
the 3
ugly 4
23
5


In [18]:
x=[]
l=int(input())
for i in range(l):
    i=int(input())
    x.append(i)
print(x)
s=0
n=a[l-1]
for i in range(l-2,0):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-18-47834433792c>, line 9)

In [5]:
x=[1,7,8,9]
y=[]
for i in range(len(x)):
    y.append(x[i])
print(y)

[1, 7, 8, 9]


In [13]:
x=[1,2]
y=[]
for i in range(0,2):
    y[i]=x[i]

IndexError: list assignment index out of range

In [27]:
n=int(input())
x=[]
for i in range(n):
    i=int(input())
    x.append(i)
print(x)
y=[]
s=0
l=0
for i in range(n-1,0,-1):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-27-87e31531b795>, line 10)

In [4]:
n=int(input())
x=[]
for i in range(n):
    i=int(input())
    x.append(i)
print(x)
c=1
cmax=0
mas=1
for i in range(n-1):
    if x[i]>x[i+1]:
        c+=1
    else:
        break
    cmax+=1
print(c)
print(mas)
print(cmax)

5
5
4
3
6
4
[5, 4, 3, 6, 4]
3
1
3


In [5]:
n=int(input())
x=[]
for i in range(n):
    i=int(input())
    x.append(i)
print(x)
original=[]
n=0
s=0
for i in reversed(x):
    i=i-n
    n=i
    original.append(i)
    s+=i
original=original[::-1]
print(original)
print(original[0])
print(s)

KeyboardInterrupt: Interrupted by user

In [8]:
a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=a*d+b*c
f=b*d
if b>d:
    a1=e//b
    a2=f//b
    print(a1,"",a2)
elif b==d:
    a1=e//f
    a2=f//f
    print(a1,"",a2)
else:
    a1=e//d
    a2=e//d
    print(a1,"",a2)

1
2
3
2
2  1


In [2]:
in1=input()
l=in1.split()
len_=len(l)
if len_<2:
    print("LESS")
else:
    print(l[1])

hello
LESS


In [38]:
alpha={'a':1,'b':2,'c':3,'d':4,'e':5,'f':6,'g':7,'h':8,'i':9,'j':10,'k':11,'l':12,'m':13,'n':14,'o':15,'p':16,'q':17,'r':18,'s':19,'t':20,'u':21,'v':22,'w':23,'x':24,'y':25,'z':26}
s=input()
s=s.lower()
s=s.replace(" ","")
s1=""
n=int(input())
for i in s:
    if n==0 and i.isalpha() and (i!='e' and i!='a' and i!='i' and i!='o' and i!='u'):
        s1+=i
    elif n==1 and i.isalpha():
        s1+=i
print(s1)
s=0
for i in s1:
    s+=alpha[i]
print(s)

all zebras are black & white??
1
allzebrasareblackwhite
214


In [1]:
print(-4%-3)

-1


In [2]:
print(-4%3)

2


In [3]:
print(4%-3)

-2


In [4]:
print(4%3)

1


In [9]:
in1=list(map(int,input().split()))
in2=list(map(int,input().split()))
in3=list(map(int,input().split()))
in4=list(map(int,input().split()))
combine=in1+in2+in3+in4
print(combine)
counter=0
num=combine[0]
for i in combine:
    freq_init=combine.count(i)
    if freq_init>counter:
        counter=freq_init
        num=i
print(num)

1 0 2 6
7 6 4 2
0 2 4 6
0 1 5 2
[1, 0, 2, 6, 7, 6, 4, 2, 0, 2, 4, 6, 0, 1, 5, 2]
2


In [2]:
a=4
print(id(a))

140733022676864


In [3]:
print(hex(id(a)))

0x7ffef5d32780


In [4]:
print(bin(id(a)))

0b11111111111111011110101110100110010011110000000


In [5]:
print(oct(id(a)))

0o3777736564623600


In [19]:
inp=input()
b=inp.replace("0","1")
print(b)       

1020406
1121416


In [2]:
inp=input()
inp[0].upper()
inp[-1].upper()
for i in range(len(inp)):
    if inp[i]==" ":
        inp[i-1].upper()
        inp[i+1].upper()
    print(inp)

hai bro
hai bro
hai bro
hai bro
hai bro
hai bro
hai bro
hai bro


In [5]:
inp=input()
for i in range(len(inp)):
    if inp[i]==" ":
        

iu hohnk hh
iUHohnk hh
iu hohnKHh


In [6]:
name = "geeks FOR geeks"
 
print(name.capitalize())
 
# demonstration of individual words
# capitalization to generate camel case
name1 = "geeks"
name2 = "for"
name3 = "geeks"
print(name1.capitalize() + name2.capitalize()
                         + name3.capitalize())
print(name)

Geeks for geeks
GeeksForGeeks


In [8]:
inp=input()
l=[]
for i in inp:
    if i==" ":
        l.append(inp[0:i])
print(i)

hs chjhn


TypeError: slice indices must be integers or None or have an __index__ method

In [18]:
inp=input().split()
print(inp)
for i in inp:
    print(i[0].upper(),end="")
    print(i[1:-1],end="")
    print(i[-1].upper(),end=" ")

hai bro how are you
['hai', 'bro', 'how', 'are', 'you']
HaI BrO HoW ArE YoU 

In [19]:
n=int(input())
max_handshakes=(n*(n-1))//2
print(max_handshakes)

10
45


In [35]:
in1=list(map(int,input().split()))
in2=list(map(int,input().split()))
in3=list(map(int,input().split()))
s=""
for i in in1:
    s=s+" "+str(i)
print(s)
s1=""
for i in in2:
    s1=s1+" "+str(i)
print(s1)
s2=""
for i in in3:
    s2=s2+" "+str(i)
print(s2)
print(s[2:]+s[0:2])
print(s1[2:]+s1[0:2])
print(s2[2:]+s2[0:2])

1 2 3
4 5 6
7 8 9
 1 2 3
 4 5 6
 7 8 9
 2 3 1
 5 6 4
 8 9 7


In [1]:
input1=input()
input2=input()
input3=input()
input4=input()
input5=input()
l=[]
l1=[]
l2=[]
l3=[]
l4=[]
stable=[]
unstable=[]
for i in input1:
    x=input1.count(i)
    l.append(x)
res=all(element==l[0] for element in l)
if(res):
    stable.append(input1)
else:
    unstable.append(input1)
for i in input2:
    x=input2.count(i)
    l1.append(x)
res=all(element==l1[0] for element in l1)
if(res):
    stable.append(input2)
else:
    unstable.append(input2)
for i in input3:
    x=input3.count(i)
    l2.append(x)
res=all(element==l2[0] for element in l2)
if(res):
    stable.append(input3)
else:
    unstable.append(input3)
for i in input4:
    x=input4.count(i)
    l3.append(x)
res=all(element==l3[0] for element in l3)
if(res):
    stable.append(input4)
else:
    unstable.append(input4)
for i in input5:
    x=input5.count(i)
    l4.append(x)
res=all(element==l4[0] for element in l4)
if(res):
    stable.append(input5)
else:
    unstable.append(input5)
print(stable)
print(unstable)
sum1=0
sum2=0
for i in stable:
    sum1+=int(i)
for i in unstable:
    sum2+=int(i)
password=sum1-sum2
print(password)

12
1313
122
78
898
['12', '1313', '78']
['122', '898']
383


In [2]:
from math import factorial
n=int(input())
r=int(input())
t=factorial(n)//factorial(n-r)
print(t)

5
3
60


In [5]:
n=int(input())
for i in range(1,n+1):
    count=0
    for j in range(1,n+1):
        if i%j==0:
            count+=1
    if count==9:
        print(i)

100
36
100


In [1]:
n='12343421'
if n==n[::-1]:
    print('yes')
else:
    low=0
    high=len(n)-1
    if n[low]==high:
        low+=1
        high+=1
    else:
        
    

yes


In [31]:
l=list(map(int,input().split()))
n=len(l)
l1=[]
for i in range(0,n):
    l1.append(i+1)
x=list(set(l1)-set(l)) 
print(x)

1 2 3 8 9
[4, 5]


In [3]:
i=input()
x=0
if i=='o':
    while x<=4:
        print(x)
        x+=1

o
0
1
2
3
4


In [3]:
r=int(input())
c=int(input())
matrix=[]
for i in range(r):
    a=[]
    for j in range(c):
        a.append(int(input()))
    matrix.append(a)
for i in range(r):
    for j in range(c):
        print(matrix[i][j],end=" ")
    print()
for i in range(r):
    max1=0
    for j in range(c):
        if matrix[i][j]>max1:
            max1=matrix[i][j]
    print(max1)    

3
4
1
2
3
4
5
6
7
8
0
1
2
9
1 2 3 4 
5 6 7 8 
0 1 2 9 
4
8
9


In [13]:
n=int(input())
l=[]
for i in range(n):
    i=int(input())
    l.append(i)
sum1=0
for i in range(len(l)):
    temp=l[i]
    while temp!=0:
        rem=temp%10
        sum1=sum1+rem
        temp=temp//10
    print(sum1)
    sum1=0

4
122
212
312
421
5
5
6
7


In [29]:
n=int(input())
l=[]
for i in range(n):
    i=int(input())
    l.append(i)
l2=[]
while l:
    x=l[0]
    for i in range(len(l)):
        if l[i]<x:
            x=l[i]
    l2.append(x)
    l.remove(x)
print(l2)

4
3
8
2
6
[2, 3, 6, 8]


In [1]:
# Python 3 program for the above approach

# Function to find the
def isValid(i, j, R, C):
	if (i < 0 or i >= R or j >= C or j < 0):
		return False
	return True

# Function to find the position of the
# K-th occurrence of element X in the
# matrix when traversed diagonally
def kthOccurrenceOfElement(arr, Q):

	# Stores the number of rows and columns
	R = len(arr)
	C = len(arr[0])

	# Stores the position of each
	# element in the diagonal traversal
	um = {}

	pos = 1;

	# Perform the diagonal traversal
	for k in range(R):
		# Push the position in the map
		if arr[k][0] in um:
			um[arr[k][0]].append(pos)
		else:
			um[arr[k][0]] = []
			um[arr[k][0]].append(pos)

		# Increment pos by 1
		pos += 1

		# Set row index for next
		# position in the diagonal
		i = k - 1

		# Set column index for next
		# position in the diagonal
		j = 1

		# Print Diagonally upward
		while (isValid(i, j, R, C)):
			if arr[k][0] in um:
				um[arr[k][0]].append(pos)
			else:
				um[arr[k][0]] = []
				um[arr[k][0]].append(pos)
			pos += 1
			i -= 1

			# Move in upright direction
			j += 1

	# Start from k = 1 to C-1
	for k in range(1,C,1):
		if arr[R-1][k] in um:
			um[arr[R - 1][k]].append(pos)
		else:
			um[arr[R-1][k]] = []
			um[arr[R - 1][k]].append(pos)
		pos += 1

		# Set row index for next
		# position in the diagonal
		i = R - 2

		# Set column index for next
		# position in diagonal
		j = k + 1

		# Print Diagonally upward
		while(isValid(i, j, R, C)):
			if arr[i][j] in um:
				um[arr[i][j]].append(pos)
			else:
				um[arr[i][j]] = []
				um[arr[i][j]].append(pos)
			pos += 1
			i -= 1

			# Move in upright direction
			j += 1

	# Traverse the queries, Q
	for i in range(len(Q)):
		if(i==0):
		print(3)
		continue
		X = Q[i][0]
		K = Q[i][1]

		# If the element is not present
		# or its occurence is less than K
		if X not in um or len(um[X]) < K:
			# Print -1
			print(-1)

		# Otherwise, print the
		# required position
		else:
			print(um[X][K - 1])

# Driver Code
if __name__ == '__main__':
	A = [[1, 4], [2, 5]]

	Q = [[4, 1], [5, 1], [10, 2]]

	kthOccurrenceOfElement(A, Q)
	
	# This code is contributed by ipg2016107.


IndentationError: expected an indented block (<ipython-input-1-b93672f5e61e>, line 90)

In [4]:
def sumOfMinAbsDifferences(arr,n):
    # sort the given array
    arr.sort()
    # initialize sum
    sum = 0
         
    # min absolute difference for
    # the 1st array element
    sum += abs(arr[0] - arr[1]);
         
    # min absolute difference for
    # the last array element
    sum += abs(arr[n - 1] - arr[n - 2]);
         
    # find min absolute difference for
    # rest of the array elements and
    # add them to sum
    for i in range(1, n - 1):
        sum += min(abs(arr[i] - arr[i - 1]),
                  abs(arr[i] - arr[i + 1]))
             
    # required sum
    return sum;
         
 
# Driver code
arr = [2,3,2]
n = len(arr)
print( "Sum = ", sumOfMinAbsDifferences(arr, n))

Sum =  1


In [2]:
Student_dt = [ [72, 85, 87, 90, 69], [80, 87, 65, 89, 85], [96, 91, 70, 78, 97], [90, 93, 91, 90, 94], [57, 89, 82, 69, 60] ]  
#print(student_dt[])  
print(Student_dt[1]) # print all elements of index 1  
print(Student_dt[0]) # print all elements of index 0  
print(Student_dt[2]) # print all elements of index 2  
print(Student_dt[3][4]) # it defines the 3rd index and 4 position of the data element.  

[80, 87, 65, 89, 85]
[72, 85, 87, 90, 69]
[96, 91, 70, 78, 97]
94


In [6]:
def two_d_matrix(m, n): # define the function  
    Outp = []  # initially output matrix is empty  
    for i in range(m): # iterate to the end of rows  
        row = []  
        for j in range(n): # j iterate to the end of column  
            num = int(input(f"Enter the matrix [{0}][{j}]"))  
            row.append(num) # add the user element to the end of the row  
        Outp.append(row) # append the row to the output matrix  
    return Outp      
m = int(input("Enter the value of m or Row\n")) # take the rows  
n = int(input("Enter the value of n or columns\n")) # take the columns  
print(two_d_matrix(m, n))

Enter the value of m or Row
3
Enter the value of n or columns
3
Enter the matrix [0][0]1
Enter the matrix [0][1]2
Enter the matrix [0][2]3
Enter the matrix [0][0]4
Enter the matrix [0][1]5
Enter the matrix [0][2]6
Enter the matrix [0][0]7
Enter the matrix [0][1]8
Enter the matrix [0][2]9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
def fact(n):
    if n==1:
        return 1
    elif n<1:
        return 'na'
    else:
        return n*fact(n-1)
n=int(input())
print(fact(n))

4
24


In [8]:
import math
n=int(input())
res=math.factorial(n)
print(res)

4
24


In [24]:
def p(l,u):
    for num in range(l,u+1):
        if num>1:
            for i in range(2,num):
                if num%i==0:
                    break
            else:
                return num
l=int(input())
u=int(input())
prin

1
5
2


In [25]:
import sympy
print(list(sympy.primerange(0, 100))) 

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [2]:
n=int(input())
arr=[]
for i in range(n):
    x=int(input())
    arr.append(x)
print(arr)
k=int(input())
arr.sort()
temp=[]
for i in range(1,n-1):
    temp[i]=arr[i+1]-arr[i]
sum1=0
start=0
n1=k-2
for i in range(k-1):
    sum=sum+temp[i]
m=sum
for i in n-1:
    i=k-1
    sum+=(temp[i]-temp[i-k+1])
    if m>=sum:
        end=i
        start=i-k+1
        m=sum
for i in range(end+1):
    i=start+1
    print(arr[i])

5
12
99
88
22
21
[12, 99, 88, 22, 21]
2


IndexError: list assignment index out of range

In [11]:
def f(arr,n):
    arr.sort()
    ar=[]
    de=99999999999
    if n==1:
        return max(arr)
    for i in range(0,len(arr)-n,n):
        su=0
        for j in range(i+1,i+n):
            su=su+arr[j]-arr[j-1]
        if su<=de:
            ar=arr[i:i+n]
    return ar
arr=[12,88,22,21,6]
n=1
print(f(arr,n))

88


In [9]:
a=9
b=10
while(a!=0):
    c=~b&a
    b=a^b
    a=c<<1
print(b)

1


In [23]:
from array import *
import copy
arr1=array('i',[1,2,3])
arr2=copy.copy(arr1)
print(arr1)
arr2[1]=5
print(arr1)

array('i', [1, 2, 3])
array('i', [1, 2, 3])


In [24]:
from array import *
import copy
arr1=array('i',[1,2,3])
print(arr1)
arr2=copy.deepcopy(arr1)
arr2[2]=5
print(arr2)
print(arr1)

array('i', [1, 2, 3])
array('i', [1, 2, 5])
array('i', [1, 2, 3])


In [2]:
x="hai bro lahari"
b=x.split()
m=b[0]
for i in b:
    if len(i)>len(m):
        m=i
print(m,len(m))

lahari 6


In [4]:
d={}
x="hai bro lahari"
b=x.split()
for i in b:
    d[i]=b.count(i)
print(d)


{'hai': 1, 'bro': 1, 'lahari': 1}


In [3]:
def f(n):
    a=0
    b=1
    if n==1:
        print(a)
    else:
        print(a,end=" ")
        print(b,end=" ")
    for i in range(2,n):
        c=a+b
        a=b
        b=c
        if c>n:
            break
        print(c,end=" ")
n=6
f(6)

0 1 1 2 3 5 

In [4]:
def f(x):
    if x==0:
        return 1
    else:
        return x*f(x-1)
x=5
print(f(5))

120


In [9]:

m=[1,2,3,4,5]
x=list(filter(lambda n:n%2==0,m))
y=list(map(lambda n:n*2,x))
print(x)
print(y)
z=reduce(lambda a,b:a+b,y)
print(z)

ModuleNotFoundError: No module named 'reduce'

In [4]:
from datetime import datetime

presentime = datetime.now()

print(presentime)

2021-09-17 16:36:17.446407


In [2]:
x=['aygf','biucsh']
print(x[0])

aygf


In [5]:
x="ayshchjc"
print(x[0:4])

aysh


In [3]:
x=[1,2,3,4,5,6,7]
y=[]
for j in range(2,i):
        if x%i==0:
            y.append(x)
print(y)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [8]:
l=[1,2,43,7,8,9]
x=[]
for i in l:
    c=0
    for j in range(1,i):
        if i%j==0:
            c+=1
    if c==1:
        x.append(i)
print(x)
y=sorted(x)
print(y)
print(y[1])

[2, 43, 7]
[2, 7, 43]
7


In [11]:
def fib(n):
    a=0
    b=1
    if n==1:
        print(a)
    else:
        print(a)
        print(b)
    for i in range(2,n):
        c=a+b
        a=b
        b=c
        if c>n:
            break
        print(c)
n=int(input())
fib(n)

5
0
1
1
2
3


In [9]:
def fib(n):
    a=0
    b=1
    if n==0:
        print(a)
    elif n==1:
        print(a)
        print(b)
    else:
        print(a)
        print(b)
        for i in range(2,n):
            c=a+b
            a=b
            b=c
            print(b)
n=int(input())
fib(n)

5
0
1
1
2
3


In [4]:
import math
s=input()
temp=set()
o=[]
for i in range(0,len(s)):
    for j in range(i,len(s)):
        subs=int(s[i:j+1])
        temp.add(subs)
temp=list(temp)
temp.sort()
print(temp)
for num in temp:
    for val in range(0,int(math.sqrt(num))+1):
        if val*(val+1)==num:
            o.append(num)
            break
print(o)

272
[2, 7, 27, 72, 272]
[2, 72, 272]


In [5]:
import math
s=input()
temp=set()
o=[]
for i in range(0,len(s)):
    for j in range(i,len(s)):
        subs=int(s[i:j+1])
        temp.add(subs)
temp=list(temp)
temp.sort()
print(temp)
for num in temp:
    for val in range(0,int(math.sqrt(num))+1):
        if val*(val+1)==num:
            o.append(num)
            break
print(o)

272
[2, 7, 27, 72, 272]
[2, 72, 272]


In [6]:
import math
s=input()
temp=set()
o=[]
for i in range(0,len(s)):
    for j in range(i,len(s)):
        subs=int(s[i:j+1])
        temp.add(subs)
temp=list(temp)
temp.sort()
print(temp)
for num in temp:
    for val in range(0,int(math.sqrt(num))+1):
        if val*(val+1)==num:
            o.append(num)
            break
print(o)

372
[2, 3, 7, 37, 72, 372]
[2, 72]


In [8]:
import math
s=input()
temp=set()
o=[]
for i in range(len(s)):
    for j in range(i,len(s)):
        subs=int(s[i:j+1])
        temp.add(subs)
temp=list(temp)
temp.sort()
print(temp)
for i in temp:
    for val in range(0,int(math.sqrt(i))+1):
        if val*(val+1)==i:
            o.append(i)
            break
print(o)

272
[2, 7, 27, 72, 272]
[2, 72, 272]


In [10]:
x=[89,2,34,5,7,8]
l=[]
for i in range(len(x)-1):
    if x[i]>max(x[i+1:]):
        l.append(x[i])
l.append(x[-1])
print(l)

[89, 34, 8]


In [13]:
l=[1,2,3,4,5]
y=[]
for i in l:
    c=0
    for j in range(1,i):
        if i%j==0:
            c+=1
    if c==1:
        y.append(i)
x=sorted(y)
print(x)
print(x[1])
        

[2, 3, 5]
3


In [2]:
n=4
d=3
x=[]
for i in range(n):
    y=int(input())
    x.append(y)
appind=d%n
appid=x[appind]
i=appid
while i>0:
    x[i]=x[i-1]
    i=i-1
x[0]=appid
for i in n:
    print(x[i])
    

1
2
3
4


IndexError: list assignment index out of range

In [14]:
n=5
a=[16,9,4,3,8,3]
c=0
for i in range(0,n):
    for j in range(i+1,n):
        if a[i]>=a[j]:
            break
    if j==n-1:
        print(a[i],end=" ")     
    

3 8 

In [7]:
num=[]
s=10
for i in range(s):
    x=int(input())
    num.append(x)
print(num)
d=7
appindex=(d-1)%s
appid=num[appindex]
i=appindex
while i>0:
    num[i]=num[i-1]
    i-=1
num[0]=appid
print(num)

4
1
3
7
6
8
5
2
10
9
[4, 1, 3, 7, 6, 8, 5, 2, 10, 9]
[5, 4, 1, 3, 7, 6, 8, 2, 10, 9]


In [1]:
x=7
c=0
for i in range(1,x):
    if x%i==0:
        c+=1
if c==1:
    print('yes')

yes


In [3]:
x=[1,2,3,4,6,8,7,11]
y=[]
for i in x:
    c=0
    for j in range(1,i):
        if i%j==0:
            c+=1
    if c==1:
        y.append(i)
print(y)
print(max(y))

[2, 3, 7, 11]
11


In [10]:
from array import *
x=array('i',[])
n=int(input())
for i in range(n):
    s=int(input())
    x.append(s)
print(x)
print(x[1])
print(x.buffer_info())

5
7
2
6
1
4
array('i', [7, 2, 6, 1, 4])
2
(1980563172400, 5)


In [13]:
l=int(input())
for i in x:
    if i==l:
        print('found')
        break
else:
    print('not')

9
not


In [18]:
import numpy
from array import *
x=numpy.array([])
n=int(input())
for i in range(n):
    s=int(input())
    numpy.append(x,s)
    print(x)
print(x)

4
1
[]
2
[]


KeyboardInterrupt: Interrupted by user

In [21]:
import numpy
a=numpy.array([1,2,3])
b=numpy.append(a,[5,6,8])
print(b)

[1 2 3 5 6 8]


In [22]:
import numpy

In [1]:
import numpy
a=numpy.array([[1,2,3],[5,6,7]])
print(a)
b=numpy.array([[9,8]])
n=numpy.append(a,b)
print(n)

[[1 2 3]
 [5 6 7]]
[1 2 3 5 6 7 9 8]


In [33]:
import numpy
a=numpy.array([1,2,3])
n=numpy.insert(a,1,90)
print(n)

[ 1 90  2  3]


In [34]:
import numpy
a=numpy.array([[1,2,3],[5,6,7]])
n=numpy.append(a,[[9,8,2]],a)
print(n)

TypeError: only integer scalar arrays can be converted to a scalar index

In [40]:
from numpy import *
a=array([[1,2,3],[4,5,6],[7,8,9]])
m=matrix(a)
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
print(m[0][1])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [45]:
from numpy import *
x=array([1,2,3.0])
print(x.dtype)

float64


In [46]:
from numpy import *

In [50]:
a=zeros([3,3],dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
from numpy import *
a1=array([1,2,3])
a2=a1.view()
print(a1)
a2[1]=4
print(a2)
print(a1)

[1 2 3]
[1 4 3]
[1 4 3]


In [8]:
from numpy import * 
import copy
a1=array([1,2,3])
a2=a1.copy()
a2[1]=4
print(a2)
print(a1)

[1 4 3]
[1 2 3]


In [10]:
def armstrong(n):
    number = str(n)
 
    n = len(number)
    output = 0
    for i in number:
        output = output+int(i)**n
 
    if output == int(number):
        return(True)
    else:
          return(False)
         
print(armstrong(153))
print(armstrong(120))

True
False


In [11]:
n=5
f=1
for i in range(1,n+1):
    f=f*i
print(f)

120


In [13]:
def f(n):
    if n==0:
        return 1
    else:
        return n*f(n-1)
print(f(5))

120


In [2]:
n=121
s=0
t=n
while n>0:
    r=n%10
    s=s*10+r
    n=n//10
if t==s:
    print('yes')
else:
    print('no')

yes


In [3]:
x=input()
y=''
for i in x:
    y=i+y
print(y)
if y==x:
    print('yes')
else:
    print('no')

yebfnhcbj
jbchnfbey
no


In [5]:
x=input()
if x==x[::-1]:
    print('yes')
else:
    print('no')

mjhsdfj
no


In [7]:
x=input()
print(x[::-1])

yes
sey


In [5]:
from itertools import permutations
x=input()
y=[''.join(p) for p in permutations(x)]
print(len(y))

ABC
6


In [17]:
x=['a','b','c','d']
y=[''.join(p) for p in x]
for i in y:
    print(i,end="")

abcd

In [2]:
z=input()
y=x.replace(z,'')
print(y)

abc
a
bc


In [3]:
x="Java is best programming language"
print(x[::-1])

egaugnal gnimmargorp tseb si avaJ


In [4]:
x="Java is best programming language"
w=x.split()
w=list(reversed(w))
print(" ".join(w))

language programming best is Java


In [3]:
x=input()
f={}
for i in x:
    if i in f:
        f[i]+=1
    else:
        f[i]=1
print(f)
res=max(f,key=f.get)
print(str(res))

ghjkkhhhhkgggg
{'g': 5, 'h': 5, 'j': 1, 'k': 3}
g


In [12]:
num=int(input())
y=[int(x) for x in str(num)]
print(min(y))

325432
[3, 2, 5, 4, 3, 2]
2


In [11]:
input1=input()
input2=input()
print(input1.count(input2))

mmmNNNNNhhshhh
N
5


In [7]:
from itertools import permutations
x=input()
y=[' '.join(p) for p in permutations(x)]
print(len(y))

ABC
6


In [25]:
x=input()
y=input()
if sorted(x)==sorted(y):
    print('yes')
else:
    print('no')

stop
pots
yes


In [27]:
x=input()
print(x,type(x))
y=int(x)
print(y,type(y))

123
123 <class 'str'>
123 <class 'int'>


In [29]:
x=[]
n=int(input())
for i in range(n):
    a=int(input())
    x.append(a)
print(x)
a=[]
for i in range(n-1):
    for j in range(i+1,n):
        if x[i]==x[j]:
            if x[i] in a:
                break
            else:
                a.append(x[i])
print(a)

5
1
2
3
2
1
[1, 2, 3, 2, 1]
[1, 2]


In [34]:

n=int(input())
x=[int(input()) for i in range(n)]
a=[]
for i in range(n-1):
    for j in range(i+1,n):
        if x[i]==x[j]:
            if x[i] in a:
                break
            else:
                a.append(x[i])
print(a)
for i in a:
    print(i,end=" ")

6
1
2
3
4
3
2
[2, 3]
2 3 

In [37]:
x=[1,2,3,4,5]
y=[2,3,1,0,5]
a=[]
for i in x:
    for j in y:
        if i==j:
            break
    else:
        a.append(i)
print(a)

[4]


In [39]:
x=[1,1,1,2,2,3,3,3,3,3]
print(list(set(x)))

[1, 2, 3]


In [43]:
x=[1,5,2,4,6]
y=6
for i in range(len(x)-1):
    for j in range(i+1,len(x)):
        if x[i]+x[j]==y:
            print(x[i],x[j])

1 5
2 4


In [47]:
x='abcd'
y='abc'
for i in x:
    for j in y:
        if i==j:
            break
    else:
        print(i)

d


In [49]:
x='abcdeio'
v=[]
c=[]
for i in x:
    if i=='a' or i=='e' or i=='i' or i=='o' or i=='u':
        v.append(i)
    else:
        c.append(i)
print(v)
print(c)

['a', 'e', 'i', 'o']
['b', 'c', 'd']


In [52]:
x=[1,2,3,4]
print(x[::-1])

[4, 3, 2, 1]


In [53]:
a=8
b=6
a=a^b
b=a^b
a=a^b
print(a)
print(b)

6
8


In [1]:
x=input()
print(x[-1]+" "+x[-2])

apple
e l


In [11]:
z=[(products[i],productPrices[i]) for i in range(len(products))]
c=[(productSold[i],soldPrice[i]) for i in range(len(productSold))]
m=0
for i in z:
    for j in c:
        if i[0]==j[0] and i[1]!=j[1]:
            m+=1
return m

[('eggs', 2.89), ('milk', 3.29), ('cheese', 5.79)]
[('eggs', 2.89), ('eggs', 2.99), ('cheese', 5.97), ('milk', 3.29)]
2


In [12]:
def f(s):
    m=''
    for i in range(len(s)):
        for j in range(len(s),i,-1):
            if len(m)>=j-i:
                break
            elif s[i:j]==s[i:j][::-1]:
                m=s[i:j]
                break
    return m
s=input()
print(f(s))

abbabbab
abbabba


In [1]:
x=input()
print(x.swapcase())

Hello World People
hELLO wORLD pEOPLE


In [29]:
import math
from math import *
n=int(input())
x=[int(i) for i in input().split()][:n]
s=0
for i in range(n):
    s+=x[i]
c=0
for i in range(s+1):
    c=i*i*i
    if c==s:
        print(s)
    else:
        b=floor(s**(1/3))+1
        u=b**3
print(u-s)

6
60 7 8 10 250 730
266


In [12]:
n=int(input())
d=int(input())
x=[int(input()) for i in range(n)]
for i in x:
    print(i,end=" ")
print()
s=[]
for i in x:
    a=i//d
    s.append(a)
b=0
for i in s:
    b+=i
print(b)

5
4
25
26
54
81
48
25 26 54 81 48 
57


In [20]:
x=input()
s=set(s)
s=''.join(s)
dup=''
for i in s:
    if i in dup:
        pass
    else:
        dup=dup+i
print(dup)

lahari
lhari


In [29]:
x=input()
for i in range(len(x)):
    c=0
    for j in range(len(x)):
        if x[i]==x[j] and i!=j:
            c+=1
            break
    if c==0:
        print(x[i],end="")

lahari
lhri

In [31]:
x=input()
for i in x:
    if int(i)%2==0:
        print(i,end="")

123456
246

In [32]:
class Car:
    pass

In [28]:
n=3
x=[int(i) for i in input().split()][:n]
a=[]
b=[]
for i in x:
    l=list(str(i))
    a.append(max(l))
    b.append(sorted(l)[-2])
s1=0
s2=0
for i in a:
    s1+=int(i)
for i in b:
    s2+=int(i)
print(s1-s2)

3521 2452 1352
5


In [45]:
class Car:
    pass
obj1=Car()
print(obj1)

In [67]:
class Car:
    def __init__(self,name,color,mileage):
        self.name=name
        self.color=color
        self.mileage=mileage
    def description(self):
        return f"the {self.name} gives mileage of {self.mileage}"
    def colour(self):
        return f"the {self.name} has color of {self.color}"
class Audi(Car):
    def audi_desc(self):
        return f"the {self.name} audi is type of car {self.color}"
obj1=Car('sedan','red',120)
print(obj1.description())
obj2=Audi('tata','blue',220)
print(obj2.description())
print(obj2.audi_desc())

the sedan gives mileage of 120
the tata gives mileage of 220
the tata audi is type of car blue


In [17]:
d = {} 

alpha = 'abcdefghijklmnopqrstuvwxyz'

for i in range(26):
    d[alpha[i]] = i
x=int(input())
y=[]
for i in str(x):
    y.append(int(i))
l=[d[i] for i in y]
for i in l:
    print(i,end="")

12340


KeyError: 1

In [16]:
import string
a=dict(enumerate(string.ascii_lowercase))
x=int(input())
y=[]
for i in str(x):
    y.append(int(i))
l=[a[i] for i in y]
for i in l:
    print(i,end="")

12403
bcead

In [24]:
x=input()
y=x.split()
print(len(y[-1]))

i am a genious developer
9


In [47]:
def f(x):   
    a=[]
    for i in range(b):
        if c>x[i]:
             a.append(i)
    print(max(a)+1)
x=[int(i) for i in input().split()][:2]
for i in x:
    b=x[0]
    c=x[1]
x=[int(i) for i in input().split()][:b]
f(x)

5 6
1 3 5 7 9
3


In [ ]:
x=int(input())
for i in str(x):
    if i%2==0:
        i+=1
    else:
        i-=1
print(x)

In [33]:
x=int(input())
if x<=50 and x>=30:
    print('Average')
elif x<=60 and x>=51:
    print('Good')
elif x<=80 and x>=61:
    print('Excellent')
elif x<=100 and x>=81:
    print('Outstanding')
    

77
Excellent


In [37]:
n=int(input())
print(bin(n).replace('0b',''))

123
1111011


In [49]:
n=int(input())
x=[int(i) for i in input().split()][:n]
y=[]
z=[]
for i in x:
    for j in range(1,i):
        if i%j==0:
            z.append(i)
        else:
            y.append(i)
print(y)
print(z)

5
12 3 5 4 8 
[12, 3, 5, 4, 8]
[12, 12, 12, 12, 12, 3, 5, 4, 4, 8, 8, 8]


In [2]:
n=int(input())
x=[int(i) for i in input().split()][:n]
a,b=[int(i) for i in input().split()][:2]
z=[]
for i in range(a,b+1):
    z.append(x[i])
z.reverse()
print(x[:a]+z)

5
1 2 3 4 5
2 4
[1, 2, 5, 4, 3]


In [ ]:
a,b=input().split(' ')
for i in range(int(a)):
    x=[int(i) for i in input().split()][:int(b)]


In [9]:
a=[1,3,1,4,5,6,3,2]
y=set()
for x in a:
    if a.count(x)>1:
        y.add(x)
print(len(y))      

2


In [2]:
n=int(input())
y=[int(i) for i in input().split()][:n]
y.sort()
print(y[-1]+y[-2])

5
15 26 13 7 45
71


In [18]:
x=int(input())
u=[]
for i in str(x):
    u.append(int(i))
a=[]
for i in u:
    if i%2==0:
        a.append(i+1)
    else:
        a.append(i-1)
for i in a:
    print(i,end="")

245567
354476

In [28]:
n=int(input())
x=[int(i) for i in input()][:n]
f={}
for i in x:
    if i in f:
        f[i]+=1
    else:
        f[i]=1
res=max(f,key=f.get)
print(res)
res2=min(f,key=f.get)
print(res2)
print(abs(int(res)-int(res2)))

7
2323555
5
2
3


In [31]:
x=int(input())
y=[int(i) for i in input().split()][:x]
y.sort()
for i in range(x):
    if y[i]==y[-1-i]:
        print(y[i],0)
        break
    else:
        print(y[-1-i],y[i])

6
90 14 89 24 643 78
643 14
90 24
89 78
78 89
24 90
14 643


In [3]:
n=int(input())
l=[]
while n!=0:
    if n%2==0:
        n=n//2
        l.append(n)
    else:
        n=n-1
        l.append(n)
print(len(l))

12
5


In [11]:
n=int(input())
x=[int(i) for i in input().split()][:n]
temp=x[0]
a=[]
for i in range(n):
    if x[i]>temp:
        temp=x[i]
        a.append(temp)
for i in range(n):
    if x[i]<a[0]:
        print(i,end=" ")

7
2 3 4 1 5 6 7
[3, 4, 5, 6, 7]
2 1 

In [13]:
n=int(input())
arr=list(map(int,input().split()))
l=arr[0]
for i in range(n):
    if arr[i]<temp:
        print(arr[i],end=" ")
        l=arr[i]

5
3 2 4 6 5
2 4 6 5 

In [4]:
def x(dt,*args):
    if dt=='int':
        answer=0
    if dt=='str':
        answer=''
    for i in args:
        answer=answer+i
    print(answer)
x('int',7,8)
x('str','hi',' laha')

15
hi laha


In [3]:
x=int(input())
y=[]
for i in str(x):
    y.append(int(i))
a=[]
for i in y:
    if i%2==0:
        a.append(i+1)
    else:
        a.append(i-1)
for i in a:
    print(i,end="")

1234
0325

In [1]:
n=int(input())
x=int(input())
a=[int(i) for i in input().split()][:n]
y=[]
for i in a:
    b=i%x
    y.append(b)
s=0
for i in y:
    s+=i
print(s)

5
4
25 26 54 81 48
6


In [13]:
def f(x):
    if x==0:
        return 1
    return x*f(x-1)
x=int(input('n:'))
print(f(x))

n:20
2432902008176640000


In [14]:
x=[i for i in input('str:')]
n=len(x)
s=0
for i in x:
    s+=ord(i)
print("%.2f"%(s/n))

str:qwerty
114.00


In [22]:
def Average(str):
    n=len(str)
    s=0
    for i in str:
        s+=ord(i)
    print("%.2f"%(s/n))
n=int(input())
str=[i for i in input()][:n]
res=Average(str)

6
source
109.50


In [3]:
str=input()
if str==str[::-1]:
    print('you inputted a strong string.')
else:
    print('you inputted a weak string.')

wow
you inputted a strong string.


In [2]:
for i in range(1,6):
    for j in range(1,i+1):
        print(j,end="")
    print()

1
12
123
1234
12345


In [11]:
for i in range(5,0,-1):
    for j in range(1,i+1):
        print(j,end="")
    print()

12345
1234
123
12
1


In [12]:
s='str'
print(s.upper())

STR


In [18]:
s='hai how r you'
b=s.split()
c=b[::-1]
for i in c:
    print(i,end=" ")

you r how hai 

In [25]:
for i in range(6):
    if i>3:
        break
    print(i)

0
1
2
3


In [27]:
a='I'
print(ord(a))

73


In [10]:
n=int(input())
print([i for i in range(1,n+1) if i%2==1])

20
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [1]:
n='lahari'
print(n.capitalize())

Lahari


In [4]:
x=[]
print(bool(x))

False


In [6]:
from functools import reduce
l=[5,8,10,20,50,100]
x=reduce(lambda a,b:a+b,l)
print(x)

193


In [11]:
for i in range(1,6):
    for j in range(0,i):
        print(j,end=" ")
    print()

0 
0 1 
0 1 2 
0 1 2 3 
0 1 2 3 4 


In [12]:
for i in range(1,6):
    for j in range(1,i+1):
        print(i,end=" ")
    print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [13]:
for i in range(1,6):
    for j in range(0,i):
        print('#',end=" ")
    print()

# 
# # 
# # # 
# # # # 
# # # # # 


In [14]:
def f(*args,**kwargs):
    print(args)
    print(kwargs)
f(1,'hello',name='djfj',age='20')

(1, 'hello')
{'name': 'djfj', 'age': '20'}


In [3]:
N=int(input())
Y=int(input())
a=[]
for i in range(N):
    a.append(int(input()))
s=0
for i in range(N):
    if i==0 or i==N-1:
        s+=a[i]
    else:
        if a[i]<min(a[i],Y):
            s+=a[i]
        else:
            s+=min(a[i],Y)
print(s)

6
4
1
2
4
6
5
3
18


In [6]:
for i in range(5):
    for j in range(i+1):
        print('*',end=" ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [13]:
for i in range(5):
    for j in range(i,5):
        print('*',end=" ")
    print()

* * * * * 
* * * * 
* * * 
* * 
* 


In [11]:
for i in range(5):
    for j in range(i+1):
        print(' ',end=" ")
        print('*',end=" ")
    print()

  * 
  *   * 
  *   *   * 
  *   *   *   * 
  *   *   *   *   * 


In [14]:
for i in range(1,6):
    for j in range(1,i+1):
        print(i,end=" ")
    print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [16]:
for i in range(1,6):
    for j in range(i,6):
        print(i,end=" ")
    print()

1 1 1 1 1 
2 2 2 2 
3 3 3 
4 4 
5 


In [18]:
for i in range(1,6):
    for j in range(1,i+1):
        print(j,end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [20]:
for i in range(5,0,-1):
    for j in range(i):
        print(i,end=" ")
    print()

5 5 5 5 5 
4 4 4 4 
3 3 3 
2 2 
1 


In [21]:
for i in range(5,0,-1):
    for j in range(i):
        print('5',end=" ")
    print()

5 5 5 5 5 
5 5 5 5 
5 5 5 
5 5 
5 


In [24]:
for i in range(1,6):
    for j in range(i,0,-1):
        print(j,end=" ")
    print()

1 
2 1 
3 2 1 
4 3 2 1 
5 4 3 2 1 


In [25]:
for i in range(6,-1,-1):
    for j in range(i):
        print(j,end=" ")
    print()

0 1 2 3 4 5 
0 1 2 3 4 
0 1 2 3 
0 1 2 
0 1 
0 



In [26]:
for i in range(6):
    for j in range(1,i+1):
        print(j,end=" ")
    for j in range(i-1,0,-1):
        print(j,end=" ")
    print()


1 
1 2 1 
1 2 3 2 1 
1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 


In [27]:
for i in range(5,0,-1):
    for j in range(i,0,-1):
        print(j,end=" ")
    for j in range(1,i+1):
        print(j,end=" ")
    print()

5 4 3 2 1 1 2 3 4 5 
4 3 2 1 1 2 3 4 
3 2 1 1 2 3 
2 1 1 2 
1 1 


In [36]:
for i in range(11,0,-1):
    for j in range(11,i-2,-1):
        if j%2==0:
            print(j,end=" ")
    print()

10 
10 
10 8 
10 8 
10 8 6 
10 8 6 
10 8 6 4 
10 8 6 4 
10 8 6 4 2 
10 8 6 4 2 
10 8 6 4 2 0 


In [38]:
for i in range(5,0,-1):
    for j in range(0,i):
        print('*',end=" ")
    print()

* * * * * 
* * * * 
* * * 
* * 
* 


In [1]:
names=['laak','dfsdf','fdghb']
x,y,z=names
print(x)

laak


In [2]:
a=1,2,3
print(a)

(1, 2, 3)


In [1]:
n=int(input())
print(bin(n))

2
0b10


In [7]:
n=int(input())
x='0b'+str(n)

1010


In [8]:
0b11

3

In [10]:
print(x)
print(0b1010)

0b1010
10


In [3]:
def f(n):
    if n>0:
        res=n+f(n-1)
    else:
        return 0
    return res
print(f(3))

6


In [4]:
def f(n):
    a=0
    b=1
    if n==1:
        print(a)
    else:
        print(a)
        print(b)
        for i in range(2,n):
            c=a+b
            a=b
            b=c
            print(c)
f(6)

0
1
1
2
3
5


In [5]:
def f(n):
    if n==0:
        return 1
    else:
        return n*f(n-1)
print(f(4))

24


In [6]:
from functools import reduce
nums=[1,2,3,4,5]
x=reduce(lambda a,b:a+b,nums)
print(x)

15


In [9]:
nums=[1,2,3,4,5]
x=list(filter(lambda n:n%2==0,nums))
print(x)

[2, 4]


In [15]:
nums=[1,2,3,4,5]
num=list(map(lambda n:n*2,nums))
print(num)

[2, 4, 6, 8, 10]


In [6]:
input2={8,8,8,8,8}
s=list(set(input2))
x=sorted(s)
print(x)
if len(x)==1:
    print('-1')
else:
    print(x[-2])

[8]
-1


In [5]:
x=input1.split()
c=0
for i in x:
    if i==i[::-1]:
        c+=1
return c
    

0


In [9]:
n=int(input())
l=[]
for i in str(n):
    l.append(i)
print(l)
b=[]
if len(l)%2==0:
    for i in range(1,len(l)):
            b.append(l[i])
            b.append(l[i-1])
print(b)

123456
['1', '2', '3', '4', '5', '6']
['2', '1', '3', '2', '4', '3', '5', '4', '6', '5']


In [3]:
l=[1,4,3,2,7,8]
for i in range(len(l)):
    if len(l)!=0:
        print(max(l),end=" ")
        l.remove(max(l))
        print(min(l),end=" ")
        l.remove(min(l))

8 1 7 2 4 3 

In [1]:
def characterAt(input1,input2):
    expand = ""
    freq = 0 
    i = 0
    while(i < len(input1)):
        temp = "" 
        freq = 0 
        while (i < len(input1) and ord(input1[i]) >= ord('a') and ord(input1[i]) <= ord('z')):
            temp += input1[i]
            i += 1
        while (i < len(input1) and ord(input1[i]) >= ord('1') and ord(input1[i]) <= ord('9')):
            freq = freq * 10 + ord(input1[i]) - ord('0')
            i += 1
        for j in range(1, freq + 1, 1):
            expand += temp
    if (freq == 0):
        expand += temp
    if len(expand)<input2:
        return '-1'
    else:
        return expand[input2 - 1]
print(characterAt('a3b2',4))

b


In [2]:
def f(input1):
    if(input1<5):
        return 0
    count = 0
    while(input1>=5):
        input1=input1//5
        count=count+input1
    return count
print(f(50))

12


In [11]:
def arrangements(input1):
    if (input1== 1): 
        return 0
    if (input1== 2): 
        return 1
    return (input1 - 1) * (arrangements(cls,input1- 1) +arrangements(cls,input1 - 2))
print(arrangements(4))

9


In [1]:
def countDer(n):
    if n == 1 or n == 2:
        return n-1
    a = 0
    b = 1
    for i in range(3, n + 1):
        cur = (i-1)*(a+b)
        a = b
        b = cur
    return b
n = 5
print("Count of Dearrangements is ", countDer(n))

Count of Dearrangements is  44


In [6]:
def f(nums):
    d={}
    d[0]=-1
    l=0
    end=-1
    total=0
    for i in range(len(nums)):
        total+= -1 if (nums[i]==0) else 1
        if total in d:
            if l<i-d.get(total):
                l=i-d.get(total)
                end=i
        else:
            d[total]=i
    if end!=-1:
        print(end)
    else:
        print('0')
nums=[1,1,1,1]
f(nums)

0


In [25]:
def getDividedstring(text,count):
    s=len(text)
    if s%count!=0:
        print("Invalid Input")

    k=s//count
    for i in range(0,s,k):
        print(text[i:i+k])
getDividedstring('a_simple_divide_string_ques',4)

SyntaxError: 'break' outside loop (<ipython-input-25-6dd739c0b5fc>, line 5)

In [3]:
import textwrap
x=textwrap.wrap('a_simple_divide_string_quest',4)
for i in x:
    print(i)

a_si
mple
_div
ide_
stri
ng_q
uest


In [28]:
def getDividedstring(text,count):
    s=len(text)
    if s%count!=0:
        print("Invalid input")
        return 
    k=s//count
    for i in range(0,s,k):
        print(text[i:i+k])
getDividedstring('a_simple_divide_string_ques',4)

Invalid Input


In [1]:
print(ord('a'))

97


In [4]:
def f(s):
    for i in range(len(s)):
        a=ord(s[i])
        r=a-(26-(ord(s[i])-ord('a')))
        m=r%26
        s[i]=chr(m+ord('a'))
    print(''.join(s))
s=input()
s=list(s)
f(s)

sara
dtbt


In [9]:
for i in range(5):
    if i==4:
        break
    for j in range(0,i):
        print(" ",end="")
    for j in range(i+1,5):
        print("*",end="")
    print()

****
 ***
  **
   *


In [1]:
a={1,2,2,3,4}
print(a)
a=list(a)
print(a)
print(a[2])

{1, 2, 3, 4}
[1, 2, 3, 4]
3


In [1]:
s='aeas'
s1='eaas'
if sorted(s1)==sorted(s):
    print('yes')


yes


In [3]:
def fib(n):
    if n <= 1:
        return n
    return fib(n-1) + fib(n-2)
 
# Returns no. of ways to
# reach sth stair
def countWays(s):
    return fib(s + 1)
 
# Driver program
s = 5
print("Number of ways = ")
print(countWays(s))

Number of ways = 
8


In [6]:
def countWays(n, arr):
    if (n == 0):
        return 1
    no_ways = 0
    for i in arr:
        if (n - i >= 0):
            no_ways = no_ways + countWays(n - i, arr)
    return no_ways
arr=[]
n=int(input())
m=1000000000
for x in range(1,m):
    for y in range(2,x):
        if x%y==0:
            break
        else:
            arr.append(x)
    if len(arr)==n:
        break
print(arr)
n=len(arr)
print(countWays(n, arr))

3


KeyboardInterrupt: 

In [9]:
i1=5
i2={0,4,5,4,1,5}
for i in range(len(i2)):
    for j in range(i,len(i2)-1):
        if i2[i]<i2[j]:
            print(i2[i])
    

TypeError: 'set' object is not subscriptable

In [1]:
a={'pavan':'oppo','lahari':'redmi','thanu':'redmix'}
print(a.keys())

dict_keys(['pavan', 'lahari', 'thanu'])


In [2]:
print(a.values())

dict_values(['oppo', 'redmi', 'redmix'])


In [3]:
print(a.items())

dict_items([('pavan', 'oppo'), ('lahari', 'redmi'), ('thanu', 'redmix')])


In [4]:
print(a['lahari'])

redmi


In [4]:
l=[1,2,3,4,5,6,7,8]
n=len(l)
x=14
for i in range(n):
    for j in range(i+1,n):
        if l[i]+l[j]==x:
            print(i+j)

12


In [7]:
a=1
r=2
n=5
b=[]
c=a
for i in range(n):
    b.append(c)
    c=c*r
return sum(b)

31


In [8]:
def slopeOfNum(num, n):
	slope = 0
	for i in range(1, n - 1) :
		if (num[i] > num[i - 1] and
			num[i] > num[i + 1]):
			slope += 1
		elif (num[i] < num[i - 1] and
			num[i] < num[i + 1]):
			slope += 1
	return slope
if __name__ == "__main__":
	num = "1210"
	n = len(num)
	print("Slope =", slopeOfNum(num, n))


Slope = 1


In [2]:
from itertools import permutations
import psyco
psyco.full()
def nextGreater(input1,input2):
        y=[''.join(p) for p in permutations(input2)]
        l=sorted(y)
        for i in l:
            if int(i)>int(input2):
                print(i)
                print(type(i))
                break
input2=input()
input1=len(input2)
nextGreater(input1,input2)

ModuleNotFoundError: No module named 'psyco'

In [15]:
def v(s):
    x=[]
    for i in s:
        x.append(i.replace(' ',''))
    b=[]
    for i in s:
        b.append(i.split())
    s=[]
    d=[]
    for i in b:
        s.append(i[0])
        
s=[]
for i in range(3):
    si=input()
    s.append(si)
print(s)
print(len(s[1]))
print(v(s))

1 2
3 4
5 6
['1 2', '3 4', '5 6']
3
5


In [22]:
arr=[10,10,20,30,10]
x=int(input())
for i in arr:
    if i==x:
        arr.remove(i)
print(arr)

10
[20, 30, 10]


In [23]:
arr=[10,10,20,30,10]
x=int(input())
for i in range(0,len(arr)):
    if arr[i]==x:
        del arr[i]
print(arr)

10


IndexError: list index out of range

In [28]:
n=int(input())
arr=[int(i) for i in input().split()][:n] 
x=int(input())
b=[]
for i in arr:
    if i!=x:
        b.append(i)
print(b)

5
10 10 20 30 10
10
[20, 30]


In [20]:
arr=[9,8,5,4,4,2,4,1]
x=5
b=[]
for i in arr:
    if i%2==0:
        b.append(i)
    else:
        continue
print(b)

[8, 4, 4, 2, 4]


In [42]:
N=int(input())
x=[]
for i in range(N):
    c=0
    for j in range(1,i):
        if i%j==0:
            c+=1
    if c==1:
        x.append(i)
print("SERIES:",end="")
for i in range(0,len(x)-1):
    print(x[i],end=",")
print(x[-1])
        
s=0
for i in x:
    s+=i
print("SUM:",s)

15
SERIES:2,3,5,7,11,13
SUM: 41


### 

In [50]:
i=input()
x=list(i.split())
x.reverse()
p=''
for i in x:
    p+=i
    p+=' '
print(p)

reverse the string
string the reverse 


In [5]:
from tensorflow.keras.preprocessing.image import ImportDataGenerator
from tensorflow.keras.preprocessing import image
import tensorflow as tf
import matplotlib.pyplot as plt
import os
import numpy as np

ImportError: cannot import name 'ImportDataGenerator' from 'tensorflow.keras.preprocessing.image' (C:\Users\lahari\anaconda3\lib\site-packages\keras\api\_v2\keras\preprocessing\image\__init__.py)

In [3]:
import keras as kr

In [4]:
import tensorflow

In [3]:
def ad(a,b):
    c=a+b
    return c
res=ad(4,5)
print(res)

9


In [4]:
def ad(a,b):
    c=a+b
    print(c)
ad(4,5)

9


In [5]:
def ad(a,b):
    c=a+b
    return c
print(ad(4,5))

9


In [6]:
def ad(a,b):
    c=a+b
    return c
ad(4,5)

9

In [1]:
def f(f,*args):
    return f(*args)x

3

In [2]:
x=1
x:=1

SyntaxError: invalid syntax (<ipython-input-2-357fc6e44418>, line 2)

In [12]:
def octalWithoutOnes(mat,N):
    l=[]
    for i in range(N):
        s=0
        for j in range(N):
            s=s+mat[j][i]
        if '1' not in str(oct(s)):
            l.append(s)
    for i in sorted(l):
        print(i)
def main():
    N=int(input())
    mat=[]
    for i in range(N):
        s=list(map(int,input().split()))
        mat.append(s)
    octalWithoutOnes(mat,N)
main()

3
1 2 3
4 5 6
7 8 9
18


In [2]:
s=[int(i) for i in input().split()][:int(sampleInput)]
x=len(s)
y=x//2
a=0
for i in range(y,x):
    a=a+s[i]
result=a
    

4
22 33 11 44
55


In [ ]:
n = int(input("Enter any number: "))
sum1 = 0
for i in range(1, n):
    if(n % i == 0):
        sum1 = sum1 + i
if (sum1 == n):
    print("The number is a Perfect number!")
else:
    print("The number is not a Perfect number!")

In [3]:
word='APPLE'
print(word[-1]+" "+word[-2])

E L


In [8]:
def doubnum(arr,n):
    arr=sorted(arr)
    for i in arr:
        if i==b:
            b=b*2
    return b
arr=[2,8,4,6,5]
n=2
print(doubnum(arr,n))

16


In [2]:
def findMajority(arr, n):
    maxCount = 0
    index = -1 
    for i in range(input1):
        count = 0
        for j in range(input1):
            if(input2[i] == input2[j]):
                count += 1
        if(count > maxCount):
            maxCount = count
            index = i
    if (maxCount > input1//2):
        return input2[index]
    else:
        return -1
arr=[1,2,1,2]
n=len(arr)
print(findMajority(arr,n))

-1


In [1]:
l=int(input())
x=[]
for i in range(1,l):
    c=0
    for j in range(1,i):
        if i%j==0:
            c+=1
    if c==1:
        x.append(i)
print(x)

20
[2, 3, 5, 7, 11, 13, 17, 19]


In [2]:
def f(n):
    a=0
    b=1
    if n==1:
        print(a)
    else:
        print(a)
        print(b)
        for i in range(2,n):
            c=a+b
            a=b
            b=c
            print(c)
f(6)

0
1
1
2
3
5


In [3]:
def f(x):
    if x==1:
        return 1
    return x*f(x-1)
x=int(input())
f(x)


5


120

In [1]:
x=lambda a:a+a
b=x(5)
print(b)

10


In [3]:
def x(n):
    return n%2==0
b=[1,2,3,4,5,6]
x=list(filter(x,b))
print(x)

[2, 4, 6]


In [8]:
def x(n):
    return n%2==0
b=[1,2,3,4,5,6]
d=list(filter(x,b))
c=list(map(lambda a:a*2,d))
print(c)

[4, 8, 12]


In [9]:
r=[8,45,443,56,32323,456]
for i in range(len(r)):
    for j in range(i+1,len(r)):
        if r[i]>r[j]:
            r[i],r[j]=r[j],r[i]
print(r)

[8, 45, 56, 443, 456, 32323]


In [11]:
def x(a):
    for i in range(len(a)):
        s=i
        for j in range(i+1,len(a)):
            if a[s]>a[j]:
                s=j
        a[i],a[s]=a[s],a[i]
def l(a):
    for i in range(len(a)):
        print(a[i],end=" ")
a=[69,14,1,50,59]
x(a)
l(a)

1 14 50 59 69 

In [3]:
def lock(name):
    ind = nodes.index(name)+1
    c1 = ind * 2
    c2 = ind * 2 + 1
    if status[name] == 'lock' \
            or status[name] == 'fail':
        return 'false'
    else:
        p = ind//2
        status[nodes[p-1]] = 'fail'
        status[name] = 'lock'
        return 'true'
 
# Unlocking function
def unlock(name):
    if status[name] == 'lock':
        status[name] = 'unlock'
        return 'true'
    else:
        return 'false'
 
# Upgrade function
def upgrade(name):
    ind = nodes.index(name)+1
 
    # left child of ind
    c1 = ind * 2
 
    # right child of ind
    c2 = ind * 2 + 1
    if c1 in range(1, n) and c2 in range(1, n):
        if status[nodes[c1-1]] == 'lock' \
            and status[nodes[c2-1]] == 'lock':
            status[nodes[c1-1]] = 'unlock'
            status[nodes[c2-1]] = 'unlock'
            status[nodes[ind-1]] = 'lock'
            return 'true'
        else:
            return 'false'
 
# Precomputation
def precompute(queries):
  d = []
   
  # Traversing the queries
  for j in queries:
      i = j.split()
      d.append(i[1])
      d.append(int(i[0]))
 
  status = {}
  for j in range(0, len(d)-1, 2):
      status[d[j]] = 0
  return status, d
 
# Function to perform operations
def operation(name, code):
    result = 'false'
     
    # Choose operation to perform
    if code == 1:
        result = lock(name)
    elif code == 2:
        result = unlock(name)
    elif code == 3:
        result = upgrade(name)
    return result
   
   
# Driver Code
if __name__ == '__main__':
   
      # Given Input
    n = int(input());
    m = int(input())
    apis = int(input())
    nodes = []
    for i in range(n):
        x=input()
        nodes.append(x)
    queries = []
    for i in range(apis):
        y=input()
        queries.append(y)
     
    # Precomputation
    status, d = precompute(queries)
 
    # Function Call
    for j in range(0, len(d) - 1, 2):
        print(operation(d[j], d[j + 1]), end = ' ')

7
2
5
World
Asia
Africa
China
India
SouthAfrica
Egypt
1 China 9
1 India 9
3 Asia 9
2 India 9
2 Asia 9
true true true false true 